# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.13.4/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.13.4/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/jkwill87/Sync/School/CIS4820/defender

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/jkwill87/Sync/School/CIS4820/defender

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.13.4/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.13.4/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jkwill87/Sync/School/CIS4820/defender/CMakeFiles /Users/jkwill87/Sync/School/CIS4820/defender/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jkwill87/Sync/School/CIS4820/defender/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named a3

# Build rule for target.
a3: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 a3
.PHONY : a3

# fast build rule for target.
a3/fast:
	$(MAKE) -f CMakeFiles/a3.dir/build.make CMakeFiles/a3.dir/build
.PHONY : a3/fast

src/exec/events.o: src/exec/events.cpp.o

.PHONY : src/exec/events.o

# target to build an object file
src/exec/events.cpp.o:
	$(MAKE) -f CMakeFiles/a3.dir/build.make CMakeFiles/a3.dir/src/exec/events.cpp.o
.PHONY : src/exec/events.cpp.o

src/exec/events.i: src/exec/events.cpp.i

.PHONY : src/exec/events.i

# target to preprocess a source file
src/exec/events.cpp.i:
	$(MAKE) -f CMakeFiles/a3.dir/build.make CMakeFiles/a3.dir/src/exec/events.cpp.i
.PHONY : src/exec/events.cpp.i

src/exec/events.s: src/exec/events.cpp.s

.PHONY : src/exec/events.s

# target to generate assembly for a file
src/exec/events.cpp.s:
	$(MAKE) -f CMakeFiles/a3.dir/build.make CMakeFiles/a3.dir/src/exec/events.cpp.s
.PHONY : src/exec/events.cpp.s

src/exec/global.o: src/exec/global.c.o

.PHONY : src/exec/global.o

# target to build an object file
src/exec/global.c.o:
	$(MAKE) -f CMakeFiles/a3.dir/build.make CMakeFiles/a3.dir/src/exec/global.c.o
.PHONY : src/exec/global.c.o

src/exec/global.i: src/exec/global.c.i

.PHONY : src/exec/global.i

# target to preprocess a source file
src/exec/global.c.i:
	$(MAKE) -f CMakeFiles/a3.dir/build.make CMakeFiles/a3.dir/src/exec/global.c.i
.PHONY : src/exec/global.c.i

src/exec/global.s: src/exec/global.c.s

.PHONY : src/exec/global.s

# target to generate assembly for a file
src/exec/global.c.s:
	$(MAKE) -f CMakeFiles/a3.dir/build.make CMakeFiles/a3.dir/src/exec/global.c.s
.PHONY : src/exec/global.c.s

src/exec/main.o: src/exec/main.cpp.o

.PHONY : src/exec/main.o

# target to build an object file
src/exec/main.cpp.o:
	$(MAKE) -f CMakeFiles/a3.dir/build.make CMakeFiles/a3.dir/src/exec/main.cpp.o
.PHONY : src/exec/main.cpp.o

src/exec/main.i: src/exec/main.cpp.i

.PHONY : src/exec/main.i

# target to preprocess a source file
src/exec/main.cpp.i:
	$(MAKE) -f CMakeFiles/a3.dir/build.make CMakeFiles/a3.dir/src/exec/main.cpp.i
.PHONY : src/exec/main.cpp.i

src/exec/main.s: src/exec/main.cpp.s

.PHONY : src/exec/main.s

# target to generate assembly for a file
src/exec/main.cpp.s:
	$(MAKE) -f CMakeFiles/a3.dir/build.make CMakeFiles/a3.dir/src/exec/main.cpp.s
.PHONY : src/exec/main.cpp.s

src/graphics/engine.o: src/graphics/engine.c.o

.PHONY : src/graphics/engine.o

# target to build an object file
src/graphics/engine.c.o:
	$(MAKE) -f CMakeFiles/a3.dir/build.make CMakeFiles/a3.dir/src/graphics/engine.c.o
.PHONY : src/graphics/engine.c.o

src/graphics/engine.i: src/graphics/engine.c.i

.PHONY : src/graphics/engine.i

# target to preprocess a source file
src/graphics/engine.c.i:
	$(MAKE) -f CMakeFiles/a3.dir/build.make CMakeFiles/a3.dir/src/graphics/engine.c.i
.PHONY : src/graphics/engine.c.i

src/graphics/engine.s: src/graphics/engine.c.s

.PHONY : src/graphics/engine.s

# target to generate assembly for a file
src/graphics/engine.c.s:
	$(MAKE) -f CMakeFiles/a3.dir/build.make CMakeFiles/a3.dir/src/graphics/engine.c.s
.PHONY : src/graphics/engine.c.s

src/graphics/hooks.o: src/graphics/hooks.c.o

.PHONY : src/graphics/hooks.o

# target to build an object file
src/graphics/hooks.c.o:
	$(MAKE) -f CMakeFiles/a3.dir/build.make CMakeFiles/a3.dir/src/graphics/hooks.c.o
.PHONY : src/graphics/hooks.c.o

src/graphics/hooks.i: src/graphics/hooks.c.i

.PHONY : src/graphics/hooks.i

# target to preprocess a source file
src/graphics/hooks.c.i:
	$(MAKE) -f CMakeFiles/a3.dir/build.make CMakeFiles/a3.dir/src/graphics/hooks.c.i
.PHONY : src/graphics/hooks.c.i

src/graphics/hooks.s: src/graphics/hooks.c.s

.PHONY : src/graphics/hooks.s

# target to generate assembly for a file
src/graphics/hooks.c.s:
	$(MAKE) -f CMakeFiles/a3.dir/build.make CMakeFiles/a3.dir/src/graphics/hooks.c.s
.PHONY : src/graphics/hooks.c.s

src/graphics/map.o: src/graphics/map.c.o

.PHONY : src/graphics/map.o

# target to build an object file
src/graphics/map.c.o:
	$(MAKE) -f CMakeFiles/a3.dir/build.make CMakeFiles/a3.dir/src/graphics/map.c.o
.PHONY : src/graphics/map.c.o

src/graphics/map.i: src/graphics/map.c.i

.PHONY : src/graphics/map.i

# target to preprocess a source file
src/graphics/map.c.i:
	$(MAKE) -f CMakeFiles/a3.dir/build.make CMakeFiles/a3.dir/src/graphics/map.c.i
.PHONY : src/graphics/map.c.i

src/graphics/map.s: src/graphics/map.c.s

.PHONY : src/graphics/map.s

# target to generate assembly for a file
src/graphics/map.c.s:
	$(MAKE) -f CMakeFiles/a3.dir/build.make CMakeFiles/a3.dir/src/graphics/map.c.s
.PHONY : src/graphics/map.c.s

src/graphics/materials.o: src/graphics/materials.c.o

.PHONY : src/graphics/materials.o

# target to build an object file
src/graphics/materials.c.o:
	$(MAKE) -f CMakeFiles/a3.dir/build.make CMakeFiles/a3.dir/src/graphics/materials.c.o
.PHONY : src/graphics/materials.c.o

src/graphics/materials.i: src/graphics/materials.c.i

.PHONY : src/graphics/materials.i

# target to preprocess a source file
src/graphics/materials.c.i:
	$(MAKE) -f CMakeFiles/a3.dir/build.make CMakeFiles/a3.dir/src/graphics/materials.c.i
.PHONY : src/graphics/materials.c.i

src/graphics/materials.s: src/graphics/materials.c.s

.PHONY : src/graphics/materials.s

# target to generate assembly for a file
src/graphics/materials.c.s:
	$(MAKE) -f CMakeFiles/a3.dir/build.make CMakeFiles/a3.dir/src/graphics/materials.c.s
.PHONY : src/graphics/materials.c.s

src/graphics/pgm.o: src/graphics/pgm.c.o

.PHONY : src/graphics/pgm.o

# target to build an object file
src/graphics/pgm.c.o:
	$(MAKE) -f CMakeFiles/a3.dir/build.make CMakeFiles/a3.dir/src/graphics/pgm.c.o
.PHONY : src/graphics/pgm.c.o

src/graphics/pgm.i: src/graphics/pgm.c.i

.PHONY : src/graphics/pgm.i

# target to preprocess a source file
src/graphics/pgm.c.i:
	$(MAKE) -f CMakeFiles/a3.dir/build.make CMakeFiles/a3.dir/src/graphics/pgm.c.i
.PHONY : src/graphics/pgm.c.i

src/graphics/pgm.s: src/graphics/pgm.c.s

.PHONY : src/graphics/pgm.s

# target to generate assembly for a file
src/graphics/pgm.c.s:
	$(MAKE) -f CMakeFiles/a3.dir/build.make CMakeFiles/a3.dir/src/graphics/pgm.c.s
.PHONY : src/graphics/pgm.c.s

src/units/_unit.o: src/units/_unit.cpp.o

.PHONY : src/units/_unit.o

# target to build an object file
src/units/_unit.cpp.o:
	$(MAKE) -f CMakeFiles/a3.dir/build.make CMakeFiles/a3.dir/src/units/_unit.cpp.o
.PHONY : src/units/_unit.cpp.o

src/units/_unit.i: src/units/_unit.cpp.i

.PHONY : src/units/_unit.i

# target to preprocess a source file
src/units/_unit.cpp.i:
	$(MAKE) -f CMakeFiles/a3.dir/build.make CMakeFiles/a3.dir/src/units/_unit.cpp.i
.PHONY : src/units/_unit.cpp.i

src/units/_unit.s: src/units/_unit.cpp.s

.PHONY : src/units/_unit.s

# target to generate assembly for a file
src/units/_unit.cpp.s:
	$(MAKE) -f CMakeFiles/a3.dir/build.make CMakeFiles/a3.dir/src/units/_unit.cpp.s
.PHONY : src/units/_unit.cpp.s

src/units/human.o: src/units/human.cpp.o

.PHONY : src/units/human.o

# target to build an object file
src/units/human.cpp.o:
	$(MAKE) -f CMakeFiles/a3.dir/build.make CMakeFiles/a3.dir/src/units/human.cpp.o
.PHONY : src/units/human.cpp.o

src/units/human.i: src/units/human.cpp.i

.PHONY : src/units/human.i

# target to preprocess a source file
src/units/human.cpp.i:
	$(MAKE) -f CMakeFiles/a3.dir/build.make CMakeFiles/a3.dir/src/units/human.cpp.i
.PHONY : src/units/human.cpp.i

src/units/human.s: src/units/human.cpp.s

.PHONY : src/units/human.s

# target to generate assembly for a file
src/units/human.cpp.s:
	$(MAKE) -f CMakeFiles/a3.dir/build.make CMakeFiles/a3.dir/src/units/human.cpp.s
.PHONY : src/units/human.cpp.s

src/units/lander.o: src/units/lander.cpp.o

.PHONY : src/units/lander.o

# target to build an object file
src/units/lander.cpp.o:
	$(MAKE) -f CMakeFiles/a3.dir/build.make CMakeFiles/a3.dir/src/units/lander.cpp.o
.PHONY : src/units/lander.cpp.o

src/units/lander.i: src/units/lander.cpp.i

.PHONY : src/units/lander.i

# target to preprocess a source file
src/units/lander.cpp.i:
	$(MAKE) -f CMakeFiles/a3.dir/build.make CMakeFiles/a3.dir/src/units/lander.cpp.i
.PHONY : src/units/lander.cpp.i

src/units/lander.s: src/units/lander.cpp.s

.PHONY : src/units/lander.s

# target to generate assembly for a file
src/units/lander.cpp.s:
	$(MAKE) -f CMakeFiles/a3.dir/build.make CMakeFiles/a3.dir/src/units/lander.cpp.s
.PHONY : src/units/lander.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... a3"
	@echo "... src/exec/events.o"
	@echo "... src/exec/events.i"
	@echo "... src/exec/events.s"
	@echo "... src/exec/global.o"
	@echo "... src/exec/global.i"
	@echo "... src/exec/global.s"
	@echo "... src/exec/main.o"
	@echo "... src/exec/main.i"
	@echo "... src/exec/main.s"
	@echo "... src/graphics/engine.o"
	@echo "... src/graphics/engine.i"
	@echo "... src/graphics/engine.s"
	@echo "... src/graphics/hooks.o"
	@echo "... src/graphics/hooks.i"
	@echo "... src/graphics/hooks.s"
	@echo "... src/graphics/map.o"
	@echo "... src/graphics/map.i"
	@echo "... src/graphics/map.s"
	@echo "... src/graphics/materials.o"
	@echo "... src/graphics/materials.i"
	@echo "... src/graphics/materials.s"
	@echo "... src/graphics/pgm.o"
	@echo "... src/graphics/pgm.i"
	@echo "... src/graphics/pgm.s"
	@echo "... src/units/_unit.o"
	@echo "... src/units/_unit.i"
	@echo "... src/units/_unit.s"
	@echo "... src/units/human.o"
	@echo "... src/units/human.i"
	@echo "... src/units/human.s"
	@echo "... src/units/lander.o"
	@echo "... src/units/lander.i"
	@echo "... src/units/lander.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

